server:
  port: 8888
  servlet:
     context-path: /zyl
file:
  path: /fileUpload/**
  adm: 
    path: ..\fileUpload\adm\
    uploadPath: \images\adm
  types: 
    path: ..\fileUpload\types\
    uploadPath: \images\types
  flower: 
    path: ..\fileUpload\flower\
    uploadPath: \images\flower
  store: 
    path: ..\fileUpload\store\
    uploadPath: \images\store    
  user: 
    path: ..\fileUpload\user\
    uploadPath: \images\user  
  comments: 
    path: ..\fileUpload\comments\
    uploadPath: \images\comments   
  advertisement: 
    path: ..\fileUpload\advertisement\
    uploadPath: \images\advertisement    
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.184.107:3306/flowershop?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root   
    password: Zheng1125
  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口
    port: 587
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: zjqq520@vip.qq.com
    # 授权码
    password: 
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性
          starttls:
            enable: true
            required: true
  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyl.flowershop.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
alipay:
  #应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  appId: 2021000116675778
  #商户私钥，您的PKCS8格式RSA2私钥
  privateKey: 
  publicKey: 
  #服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notifyUrl: 'http://localhost:8888/zyl/order/pay/notify'
  #页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  returnUrl: 'http://localhost:8888/zyl/order/pay/return'
  #签名方式(固定值，无需修改)
  signType: RSA2
  #字符编码格式(固定值，无需修改)
  charset: utf-8
  protocol: 'https'
  #支付宝网关(固定值，无需修改)
  gatewayUrl: 'https://openapi.alipaydev.com/gateway.do'
  gatewayHost: 'openapi.alipay.com'
  timeExpire: 120000


  

   
