server:
  port: 8888
  servlet:
     context-path: /zyl
  
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowershop?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ZJ1125

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyl.flowershop.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
